import { jsPDF } from 'jspdf';

// ──────────────────────────────────────────────
// Color palette
// ──────────────────────────────────────────────
const COLORS = {
  sage:       [94, 122, 103],   // #5E7A67
  red:        [200, 50, 50],
  orange:     [210, 130, 40],
  green:      [50, 160, 80],
  black:      [30, 30, 30],
  gray:       [120, 120, 120],
  lightGray:  [200, 200, 200],
  white:      [255, 255, 255],
  amberBg:    [255, 243, 205],  // warning box background
  amberBorder:[200, 160, 60],
  amberText:  [130, 90, 20],
  tableHeader:[240, 245, 240],
  tableAlt:   [248, 250, 248],
};

// ──────────────────────────────────────────────
// Layout constants
// ──────────────────────────────────────────────
const PAGE = {
  marginLeft:   20,
  marginRight:  20,
  marginTop:    20,
  marginBottom: 35,   // room for footer
  width:        210,  // A4 mm
  height:       297,
};
const CONTENT_WIDTH = PAGE.width - PAGE.marginLeft - PAGE.marginRight;

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

/** Resolve risk-level color */
function riskColor(level) {
  const l = (level || '').toLowerCase();
  if (l === 'high') return COLORS.red;
  if (l === 'moderate') return COLORS.orange;
  return COLORS.green;
}

/** Safe page-break check — returns the new Y, adding a page if needed */
function ensureSpace(doc, y, needed) {
  if (y + needed > PAGE.height - PAGE.marginBottom) {
    doc.addPage();
    return PAGE.marginTop;
  }
  return y;
}

/** Draw a horizontal rule */
function hr(doc, y, thickness = 0.4) {
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(thickness);
  doc.line(PAGE.marginLeft, y, PAGE.width - PAGE.marginRight, y);
  return y + 2;
}

/** Section title with a subtle left accent bar */
function sectionTitle(doc, y, title) {
  y = ensureSpace(doc, y, 14);
  // accent bar
  doc.setFillColor(...COLORS.sage);
  doc.rect(PAGE.marginLeft, y, 2, 7, 'F');
  // text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.black);
  doc.text(title, PAGE.marginLeft + 6, y + 5.5);
  return y + 12;
}

/** Wrap long text into lines that fit a given max width (mm) */
function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(text || '', maxWidth);
}

// ──────────────────────────────────────────────
// Footer renderer (called once per page after content is done)
// ──────────────────────────────────────────────
function drawFooters(doc) {
  const totalPages = doc.internal.getNumberOfPages();
  const disclaimerLine1 =
    'DISCLAIMER: This report is generated by an AI screening system and is NOT a clinical diagnosis. ' +
    'It must be reviewed by a qualified professional before any intervention is planned.';
  const disclaimerLine2 =
    'Data processed under informed consent per the Digital Personal Data Protection Act 2023 (India).';

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerTop = PAGE.height - PAGE.marginBottom + 4;

    // thin rule
    doc.setDrawColor(...COLORS.lightGray);
    doc.setLineWidth(0.3);
    doc.line(PAGE.marginLeft, footerTop, PAGE.width - PAGE.marginRight, footerTop);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.gray);

    const wrapped1 = wrapText(doc, disclaimerLine1, CONTENT_WIDTH);
    let fy = footerTop + 4;
    wrapped1.forEach((line) => {
      doc.text(line, PAGE.marginLeft, fy);
      fy += 3;
    });

    doc.text(disclaimerLine2, PAGE.marginLeft, fy);
    fy += 4;

    // page number — right-aligned
    doc.text(
      `Page ${i} of ${totalPages}`,
      PAGE.width - PAGE.marginRight,
      fy,
      { align: 'right' }
    );
  }
}

// ──────────────────────────────────────────────
// Main export
// ──────────────────────────────────────────────

/**
 * Generate a clinical-grade PDF report for an ASD screening case.
 *
 * @param {Object} caseData  – screening result data
 * @param {Object} explanation – SHAP / LIME explanation payload
 * @returns {Promise<void>} resolves when the file has been saved to disk
 */
export async function generatePDF(caseData, explanation) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = PAGE.marginTop;

  // ───── 1. HEADER BLOCK ─────────────────────

  // "NeuroSense" branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.sage);
  doc.text('NeuroSense', PAGE.marginLeft, y + 6);

  // "CONFIDENTIAL" right-aligned
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.red);
  doc.text(
    'CONFIDENTIAL — For Clinical Use Only',
    PAGE.width - PAGE.marginRight,
    y + 6,
    { align: 'right' }
  );

  y += 10;
  y = hr(doc, y, 0.6);
  y += 2;

  // Report title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.black);
  doc.text('ASD Screening Report', PAGE.marginLeft, y + 5);
  y += 10;

  // Meta line 1
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.black);
  doc.text(
    `Case ID: ${caseData.id}  |  Category: ${caseData.categoryLabel}  |  Date: ${caseData.screeningDate}`,
    PAGE.marginLeft,
    y + 4
  );
  y += 7;

  // Meta line 2
  doc.text(
    `Subject: ${caseData.subjectName}  |  Age: ${caseData.age}  |  Gender: ${caseData.gender}`,
    PAGE.marginLeft,
    y + 4
  );
  y += 7;

  // Meta line 3
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.gray);
  doc.text(
    `Model: ${caseData.modelUsed}  |  Tool: ${caseData.screeningTool}`,
    PAGE.marginLeft,
    y + 4
  );
  y += 9;

  // Mock-mode warning box
  if (caseData.isMock) {
    y = ensureSpace(doc, y, 16);
    doc.setFillColor(...COLORS.amberBg);
    doc.setDrawColor(...COLORS.amberBorder);
    doc.setLineWidth(0.4);
    doc.roundedRect(PAGE.marginLeft, y, CONTENT_WIDTH, 12, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLORS.amberText);
    doc.text(
      'NOTE: This result was generated in mock mode — no trained ML model was used.',
      PAGE.marginLeft + 4,
      y + 7.5
    );
    y += 16;
  }

  y = hr(doc, y);
  y += 3;

  // ───── 2. RISK SCORE SECTION ───────────────

  y = ensureSpace(doc, y, 50);

  // Label
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gray);
  doc.setCharSpace(1.5);
  doc.text('FUSION RISK SCORE', PAGE.marginLeft, y + 4);
  doc.setCharSpace(0);
  y += 9;

  // Big score number
  const scoreStr = Number(caseData.riskScore).toFixed(2);
  const scoreColor = riskColor(caseData.riskLevel);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(...scoreColor);
  doc.text(scoreStr, PAGE.marginLeft, y + 10);

  // Risk badge text next to score
  const scoreWidth = doc.getTextWidth(scoreStr);
  doc.setFontSize(12);
  doc.text(
    `  ${(caseData.riskLevel || '').toUpperCase()} RISK`,
    PAGE.marginLeft + scoreWidth + 3,
    y + 10
  );
  y += 16;

  // AQ-10 raw score
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.black);
  doc.text(`AQ-10 Score: ${caseData.aq10Score}/10`, PAGE.marginLeft, y + 4);
  y += 9;

  // Interpretation paragraph
  if (caseData.interpretation) {
    const interpLines = wrapText(doc, caseData.interpretation, CONTENT_WIDTH);
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.black);
    interpLines.forEach((line) => {
      y = ensureSpace(doc, y, 5);
      doc.text(line, PAGE.marginLeft, y + 4);
      y += 5;
    });
    y += 3;
  }

  y = hr(doc, y);
  y += 3;

  // ───── 3. SHAP SECTION ─────────────────────

  y = sectionTitle(doc, y, 'SHAP Feature Importance — Top Contributing Signals');
  y += 1;

  // Subtitle
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.gray);
  const shapSubLines = wrapText(
    doc,
    'Shapley values show the contribution of each feature to the risk score. Positive values increase risk.',
    CONTENT_WIDTH
  );
  shapSubLines.forEach((line) => {
    y = ensureSpace(doc, y, 4);
    doc.text(line, PAGE.marginLeft, y + 3);
    y += 4;
  });
  y += 3;

  // SHAP table
  const shapData = (explanation.shap || []).slice(0, 8);
  const colX = {
    feature:   PAGE.marginLeft + 2,
    direction: PAGE.marginLeft + 95,
    value:     PAGE.marginLeft + 140,
  };
  const rowH = 7;

  // Table header
  y = ensureSpace(doc, y, rowH + 4);
  doc.setFillColor(...COLORS.tableHeader);
  doc.rect(PAGE.marginLeft, y, CONTENT_WIDTH, rowH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.black);
  doc.text('Feature', colX.feature, y + 5);
  doc.text('Direction', colX.direction, y + 5);
  doc.text('SHAP Value', colX.value, y + 5);
  y += rowH;

  // Table rows
  shapData.forEach((row, idx) => {
    y = ensureSpace(doc, y, rowH);
    if (idx % 2 === 1) {
      doc.setFillColor(...COLORS.tableAlt);
      doc.rect(PAGE.marginLeft, y, CONTENT_WIDTH, rowH, 'F');
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.black);

    // Truncate long feature names
    const featureLabel = (row.feature || '').length > 40
      ? row.feature.substring(0, 37) + '…'
      : row.feature;
    doc.text(featureLabel, colX.feature, y + 5);

    // Direction
    const dir = (row.direction || '').charAt(0).toUpperCase() + (row.direction || '').slice(1);
    doc.text(dir, colX.direction, y + 5);

    // SHAP value — colored
    const sv = Number(row.shapValue);
    const valColor = sv >= 0 ? COLORS.red : COLORS.green;
    doc.setTextColor(...valColor);
    doc.setFont('helvetica', 'bold');
    doc.text(sv.toFixed(4), colX.value, y + 5);

    y += rowH;
  });

  y += 5;
  y = hr(doc, y);
  y += 3;

  // ───── 4. LIME SECTION ─────────────────────

  y = sectionTitle(doc, y, 'LIME — Plain-Language Explanation');
  y += 1;

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.gray);
  const limeSubLines = wrapText(
    doc,
    'These are the top reasons this individual received their risk classification.',
    CONTENT_WIDTH
  );
  limeSubLines.forEach((line) => {
    y = ensureSpace(doc, y, 4);
    doc.text(line, PAGE.marginLeft, y + 3);
    y += 4;
  });
  y += 4;

  // Numbered explanations
  const limeData = (explanation.lime || []).slice(0, 5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.black);

  limeData.forEach((item, idx) => {
    const bulletText = `${idx + 1}.  ${item.plainEnglish || ''}`;
    const lines = wrapText(doc, bulletText, CONTENT_WIDTH - 4);
    lines.forEach((line, li) => {
      y = ensureSpace(doc, y, 5);
      doc.text(line, PAGE.marginLeft + (li === 0 ? 0 : 5), y + 4);
      y += 5.5;
    });
    y += 1;
  });

  // ───── EXPLANATION SUMMARY (if provided) ──

  if (explanation.summary) {
    y += 3;
    y = ensureSpace(doc, y, 20);
    y = hr(doc, y);
    y += 3;
    y = sectionTitle(doc, y, 'Summary');
    y += 1;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...COLORS.black);
    const summaryLines = wrapText(doc, explanation.summary, CONTENT_WIDTH);
    summaryLines.forEach((line) => {
      y = ensureSpace(doc, y, 5);
      doc.text(line, PAGE.marginLeft, y + 4);
      y += 5;
    });
  }

  // Mock data source note
  if (explanation.isMock) {
    y += 5;
    y = ensureSpace(doc, y, 12);
    doc.setFillColor(...COLORS.amberBg);
    doc.setDrawColor(...COLORS.amberBorder);
    doc.setLineWidth(0.3);
    doc.roundedRect(PAGE.marginLeft, y, CONTENT_WIDTH, 10, 2, 2, 'FD');
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7.5);
    doc.setTextColor(...COLORS.amberText);
    doc.text(
      'Explanations shown above are simulated (mock data) and do not reflect real model outputs.',
      PAGE.marginLeft + 4,
      y + 6.5
    );
  }

  // ───── 5. FOOTER (every page) ──────────────

  drawFooters(doc);

  // ───── SAVE ────────────────────────────────

  const filename = `NeuroSense_Report_${caseData.id || 'unknown'}.pdf`;
  doc.save(filename);

  // Return a resolved promise so callers can `await`
  return Promise.resolve();
}
